/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SystemRouteImport } from './routes/system'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as EquipmentEquipmentIdRouteImport } from './routes/equipment.$equipmentId'
import { Route as FavoritesEquipmentIdRouteImport } from './routes/favorites.$equipmentId'
import { Route as FavoritesNewRouteImport } from './routes/favorites.new'
import { Route as SchedulesScheduleIdRouteImport } from './routes/schedules.$scheduleId'
import { Route as SchedulesNewRouteImport } from './routes/schedules.new'
import { Route as ThemesThemeIdRouteImport } from './routes/themes.$themeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentEquipmentIdRoute = EquipmentEquipmentIdRouteImport.update({
  id: '/$equipmentId',
  path: '/$equipmentId',
  getParentRoute: () => EquipmentRoute,
} as any)
const FavoritesEquipmentIdRoute = FavoritesEquipmentIdRouteImport.update({
  id: '/$equipmentId',
  path: '/$equipmentId',
  getParentRoute: () => FavoritesRoute,
} as any)
const FavoritesNewRoute = FavoritesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FavoritesRoute,
} as any)
const SchedulesScheduleIdRoute = SchedulesScheduleIdRouteImport.update({
  id: '/$scheduleId',
  path: '/$scheduleId',
  getParentRoute: () => SchedulesRoute,
} as any)
const SchedulesNewRoute = SchedulesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SchedulesRoute,
} as any)
const ThemesThemeIdRoute = ThemesThemeIdRouteImport.update({
  id: '/$themeId',
  path: '/$themeId',
  getParentRoute: () => ThemesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRouteWithChildren
  '/favorites': typeof FavoritesRouteWithChildren
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/schedules': typeof SchedulesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/themes': typeof ThemesRouteWithChildren
  '/equipment/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/favorites/$equipmentId': typeof FavoritesEquipmentIdRoute
  '/favorites/new': typeof FavoritesNewRoute
  '/schedules/$scheduleId': typeof SchedulesScheduleIdRoute
  '/schedules/new': typeof SchedulesNewRoute
  '/themes/$themeId': typeof ThemesThemeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRouteWithChildren
  '/favorites': typeof FavoritesRouteWithChildren
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/schedules': typeof SchedulesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/themes': typeof ThemesRouteWithChildren
  '/equipment/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/favorites/$equipmentId': typeof FavoritesEquipmentIdRoute
  '/favorites/new': typeof FavoritesNewRoute
  '/schedules/$scheduleId': typeof SchedulesScheduleIdRoute
  '/schedules/new': typeof SchedulesNewRoute
  '/themes/$themeId': typeof ThemesThemeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipment': typeof EquipmentRouteWithChildren
  '/favorites': typeof FavoritesRouteWithChildren
  '/health': typeof HealthRoute
  '/logs': typeof LogsRoute
  '/schedules': typeof SchedulesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/themes': typeof ThemesRouteWithChildren
  '/equipment/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/favorites/$equipmentId': typeof FavoritesEquipmentIdRoute
  '/favorites/new': typeof FavoritesNewRoute
  '/schedules/$scheduleId': typeof SchedulesScheduleIdRoute
  '/schedules/new': typeof SchedulesNewRoute
  '/themes/$themeId': typeof ThemesThemeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/equipment'
    | '/favorites'
    | '/health'
    | '/logs'
    | '/schedules'
    | '/settings'
    | '/system'
    | '/themes'
    | '/equipment/$equipmentId'
    | '/favorites/$equipmentId'
    | '/favorites/new'
    | '/schedules/$scheduleId'
    | '/schedules/new'
    | '/themes/$themeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/equipment'
    | '/favorites'
    | '/health'
    | '/logs'
    | '/schedules'
    | '/settings'
    | '/system'
    | '/themes'
    | '/equipment/$equipmentId'
    | '/favorites/$equipmentId'
    | '/favorites/new'
    | '/schedules/$scheduleId'
    | '/schedules/new'
    | '/themes/$themeId'
  id:
    | '__root__'
    | '/'
    | '/equipment'
    | '/favorites'
    | '/health'
    | '/logs'
    | '/schedules'
    | '/settings'
    | '/system'
    | '/themes'
    | '/equipment/$equipmentId'
    | '/favorites/$equipmentId'
    | '/favorites/new'
    | '/schedules/$scheduleId'
    | '/schedules/new'
    | '/themes/$themeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipmentRoute: typeof EquipmentRouteWithChildren
  FavoritesRoute: typeof FavoritesRouteWithChildren
  HealthRoute: typeof HealthRoute
  LogsRoute: typeof LogsRoute
  SchedulesRoute: typeof SchedulesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SystemRoute: typeof SystemRoute
  ThemesRoute: typeof ThemesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$equipmentId': {
      id: '/equipment/$equipmentId'
      path: '/$equipmentId'
      fullPath: '/equipment/$equipmentId'
      preLoaderRoute: typeof EquipmentEquipmentIdRouteImport
      parentRoute: typeof EquipmentRoute
    }
    '/favorites/$equipmentId': {
      id: '/favorites/$equipmentId'
      path: '/$equipmentId'
      fullPath: '/favorites/$equipmentId'
      preLoaderRoute: typeof FavoritesEquipmentIdRouteImport
      parentRoute: typeof FavoritesRoute
    }
    '/favorites/new': {
      id: '/favorites/new'
      path: '/new'
      fullPath: '/favorites/new'
      preLoaderRoute: typeof FavoritesNewRouteImport
      parentRoute: typeof FavoritesRoute
    }
    '/schedules/$scheduleId': {
      id: '/schedules/$scheduleId'
      path: '/$scheduleId'
      fullPath: '/schedules/$scheduleId'
      preLoaderRoute: typeof SchedulesScheduleIdRouteImport
      parentRoute: typeof SchedulesRoute
    }
    '/schedules/new': {
      id: '/schedules/new'
      path: '/new'
      fullPath: '/schedules/new'
      preLoaderRoute: typeof SchedulesNewRouteImport
      parentRoute: typeof SchedulesRoute
    }
    '/themes/$themeId': {
      id: '/themes/$themeId'
      path: '/$themeId'
      fullPath: '/themes/$themeId'
      preLoaderRoute: typeof ThemesThemeIdRouteImport
      parentRoute: typeof ThemesRoute
    }
  }
}

interface EquipmentRouteChildren {
  EquipmentEquipmentIdRoute: typeof EquipmentEquipmentIdRoute
}

const EquipmentRouteChildren: EquipmentRouteChildren = {
  EquipmentEquipmentIdRoute: EquipmentEquipmentIdRoute,
}

const EquipmentRouteWithChildren = EquipmentRoute._addFileChildren(
  EquipmentRouteChildren,
)

interface FavoritesRouteChildren {
  FavoritesEquipmentIdRoute: typeof FavoritesEquipmentIdRoute
  FavoritesNewRoute: typeof FavoritesNewRoute
}

const FavoritesRouteChildren: FavoritesRouteChildren = {
  FavoritesEquipmentIdRoute: FavoritesEquipmentIdRoute,
  FavoritesNewRoute: FavoritesNewRoute,
}

const FavoritesRouteWithChildren = FavoritesRoute._addFileChildren(
  FavoritesRouteChildren,
)

interface SchedulesRouteChildren {
  SchedulesScheduleIdRoute: typeof SchedulesScheduleIdRoute
  SchedulesNewRoute: typeof SchedulesNewRoute
}

const SchedulesRouteChildren: SchedulesRouteChildren = {
  SchedulesScheduleIdRoute: SchedulesScheduleIdRoute,
  SchedulesNewRoute: SchedulesNewRoute,
}

const SchedulesRouteWithChildren = SchedulesRoute._addFileChildren(
  SchedulesRouteChildren,
)

interface ThemesRouteChildren {
  ThemesThemeIdRoute: typeof ThemesThemeIdRoute
}

const ThemesRouteChildren: ThemesRouteChildren = {
  ThemesThemeIdRoute: ThemesThemeIdRoute,
}

const ThemesRouteWithChildren =
  ThemesRoute._addFileChildren(ThemesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipmentRoute: EquipmentRouteWithChildren,
  FavoritesRoute: FavoritesRouteWithChildren,
  HealthRoute: HealthRoute,
  LogsRoute: LogsRoute,
  SchedulesRoute: SchedulesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SystemRoute: SystemRoute,
  ThemesRoute: ThemesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
