import type { Telemetry } from "@rygine/omnilogic-local-sdk";

// telemetry matching the SDK's reference config
const base: Telemetry = {
  version: "1",
  backyard: {
    airTemp: 78,
    configChksum: 1,
    mspVersion: "R0502000",
    state: 1,
    statusVersion: 1,
    systemId: 0,
  },
  bodiesOfWater: [
    { systemId: 1, waterTemp: 84, flow: 1 },
    { systemId: 2, waterTemp: -1, flow: 0 },
  ],
  chlorinators: [
    {
      systemId: 6,
      enable: 0,
      timedPercent: 10,
      scMode: 0,
      status: 0,
      operatingMode: 1,
      operatingState: 0,
      avgSaltLevel: 3000,
      instantSaltLevel: 3000,
      chlrAlert: 0,
      chlrError: 0,
    },
    {
      systemId: 13,
      enable: 0,
      timedPercent: 1,
      scMode: 0,
      status: 0,
      operatingMode: 1,
      operatingState: 0,
      avgSaltLevel: 3000,
      instantSaltLevel: 3000,
      chlrAlert: 0,
      chlrError: 0,
    },
  ],
  colorLogicLights: [
    {
      systemId: 8,
      lightState: 0,
      currentShow: 6,
      brightness: 4,
      speed: 4,
      specialEffect: 0,
    },
  ],
  csads: [],
  filters: [
    {
      systemId: 3,
      filterState: 1,
      filterSpeed: 58,
      lastSpeed: 80,
      reportedFilterSpeed: 58,
      valvePosition: 0,
      whyFilterIsOn: 0,
      power: 1,
      fpOverride: 0,
    },
    {
      systemId: 10,
      filterState: 0,
      filterSpeed: 0,
      lastSpeed: 0,
      reportedFilterSpeed: 0,
      valvePosition: 0,
      whyFilterIsOn: 0,
      power: 0,
      fpOverride: 0,
    },
  ],
  themes: [{ systemId: 29, groupState: 0 }],
  heaters: [
    {
      systemId: 5,
      enable: 0,
      heaterState: 0,
      temp: 84,
      priority: 1,
      maintainFor: 0,
    },
    {
      systemId: 12,
      enable: 0,
      heaterState: 0,
      temp: 100,
      priority: 1,
      maintainFor: 0,
    },
  ],
  pumps: [{ systemId: 40, pumpState: 0, pumpSpeed: 0, lastSpeed: 0, whyOn: 0 }],
  relays: [{ systemId: 22, relayState: 0, whyOn: 0 }],
  smartValveActuators: [],
  valveActuators: [],
  virtualHeaters: [
    {
      systemId: 4,
      enable: 0,
      currentSetPoint: 84,
      mode: 1,
      silentMode: 0,
      solarSetPoint: 0,
      whyHeaterIsOn: 0,
    },
    {
      systemId: 11,
      enable: 0,
      currentSetPoint: 84,
      mode: 1,
      silentMode: 0,
      solarSetPoint: 0,
      whyHeaterIsOn: 0,
    },
  ],
};

export const telemetryFixture = (): Telemetry => structuredClone(base);
